### ISSUE TITLE
Entering camera/light editors via clicking causes an extra click within CE/LE

### ISSUE THREAD

**Issue by pncl9500** [timofey260/RWE-Plus#1]
https://user-images.githubusercontent.com/80725620/210740635-5388b9c7-7c3e-4e3a-903f-2512c8665afd.mp4

If you enter camera/light editors by clicking on their respective menu buttons, RWE+ will register an extra click in the respective editor, making potentially unwanted changes to the cameras or the light. (selecting and moving a camera/painting shadow) This also happens in EE, but all of the other editors are fine, as the mouse isn't over anything.

Ignore the strange mouse pointer behavior in the video, it's just a recording bug.

**Comment by timofey260** [comment]
fixed in 1.7
