### ISSUE TITLE
Certain props are rendered as much smaller than their preview

### ISSUE THREAD

**Issue by mayhemmmwith3ms** [timofey260/RWE-Plus#11]
The preview of these props is the correct size the tile should render as, however when rendering the level these props will appear much smaller in the final product. Not all props are affected by this issue, however I am yet to find what the common trait between these small props is.

Correctly sized editor preview vs. significantly smaller ingame rendered prop:
![image](https://user-images.githubusercontent.com/62633210/229358220-b18a88dd-4e5f-479d-8d3f-8ec118edf28e.png)
![image](https://user-images.githubusercontent.com/62633210/229358251-9e8d2ecb-f8d7-42f9-8f0b-6a31c4c928c5.png)

**Comment by timofey260** [comment]
this might be a drizzle problem.
try to render this level with official editor and drizzle, then compare them

**Comment by mayhemmmwith3ms** [comment]
Just tested rendering the same level using the official Downpour editor, props are still small.

**Comment by timofey260** [comment]
does they small on preview as well or they same size?

**Comment by mayhemmmwith3ms** [comment]
Yes, the prop previews are small in the downpour editor as well.

**Comment by timofey260** [comment]
found issue, something wrong with both rendering and placing system
trying to fix

**Comment by timofey260** [comment]
![image](https://user-images.githubusercontent.com/69044246/229587322-a95ca3f4-2dba-4633-b0e5-78347fd873df.png)
here is table of why props have x4 decreased size and the reason is buffertiles
will be fixed in next release

**Comment by timofey260** [comment]
fixed with commit
