### ISSUE TITLE
Effect Editor crash after editing parameters and deleting

### ISSUE THREAD

**Issue by FIRECATinBLACK** [timofey260/RWE-Plus#14]
Severity: Minor crash
Using RWE+ version 2.1.3

Steps to replicate:
1) Open any DP Leditor room file 
2) Enter Effects editor
3) Select a effect already existing in the level or add a new one
4) Edit any parameter of it
5) Click "Delete effect from project(e)"
|> RWE+ Closes with the following error: 
![image](https://user-images.githubusercontent.com/71691122/230746176-a631672d-b6b4-4640-ae56-f66014b66ebb.png)

Expected Behavior:
1) Open any leditor room file
2) Enter Effects editor
3) Select a effect already existing in the level or add a new one
4) Edit any parameter of it
5) Click "Delete effect from project(e)"
|> Effect successfully gets removed from the project

Additional notes:
- Not every effect or parameter seems to be causing this crash and I havent noticed it in non DP files yet. What I found consistant however was taking any plant like "Seed Pod" and changing the color
- I tested 5 different files, 3 in DP leditor SU and 2 that came with RWE with all possible parameters on both a few plants and slime and rain moss. Only plants showed positive for the crash from what I could tell, there could be more
- I havent submitted many GitHub issues before, if you have any criticism on how I can provide more helpful information feel free to let me know!

**Comment by timofey260** [comment]
found issue
working on fix
