### ISSUE TITLE
Broken file browser scroll upon click

### ISSUE THREAD

**Issue by FIRECATinBLACK** [timofey260/RWE-Plus#15]
Severity: Minor Bug
Using RWE+ version 2.1.3

Steps to replicate:
1 ) Select the "Open Project" option upon opening the program
2 ) Mouseclick on any level without opening it
3 ) Scroll either with mouse or arrow keys
|> RWE's browser becomes completely empty until you return to the initial New or Open screen
https://user-images.githubusercontent.com/71691122/230799470-d36b43a4-b17c-4d59-900f-c87b2c800e8c.mp4

Expected behavior:
|> RWE continues scrolling from where you clicked (with arrow keys) or generally continues to scroll through the files in the folder

Additional notes:
- Sometimes going back to the very begin of the path and pressing enter seems to cause a crash, seems inconsistent so I havent been able to get a screenshot of the console. Will update if more information is found
- Oftentimes you can still at least see the file you clicked on upon scrolling up. Sometimes this isnt the case, also appears inconsistent
- Displays no errors in the console
- I havent submitted many GitHub issues before, if you have any criticism on how I can provide more helpful information feel free to let me know!

**Comment by timofey260** [comment]
rwe+ updates every time you scroll something, so when you press button, you entered your filename to text field
after update, rwe+ would search only items with name of your file and there will be only one file left(what you selected)
if you clear text, all buttons will return to normal
this is not a bug or unexpected behavior

**Comment by timofey260** [comment]
also crashes might happend when you entered wrong filename or you don't have access to it
