### ISSUE TITLE
certain 'tiles as prop' props do not align correctly with gridsnap

### ISSUE THREAD

**Issue by mayhemmmwith3ms** [timofey260/RWE-Plus#16]
Props in 'tiles as prop' that have a width or height that is an odd number will have their edge align with the center of a grid tile instead of the edge of a grid tile. 

![image](https://user-images.githubusercontent.com/62633210/231805893-187aaad7-a994-4dd9-8a95-57e6d8b5ff1e.png)
![image](https://user-images.githubusercontent.com/62633210/231806042-469503cd-c377-4e64-b9f6-090eef7b37da.png)
![image](https://user-images.githubusercontent.com/62633210/231806210-08665ac2-b906-4068-bf8c-e2f3853df66a.png)
A 1x1 tile being incorrectly aligned on both axis, a 2x1 tile being correctly aligned on the X axis, but not the Y axis, and a 2x2 tile being correctly aligned on both axis.

**Comment by timofey260** [comment]
found issue
working on fix

**Comment by timofey260** [comment]
will be fixed with next release
