### ISSUE TITLE
Exiting editor resets level to the last time the undo button was pressed

### ISSUE THREAD

**Issue by mayhemmmwith3ms** [timofey260/RWE-Plus#2]
When exiting a specific editor to the main menu, any changes made to the level past the last time the undo button was pressed are lost. If the level was saved while an editor menu was open, the save file retains these changes unless the level is saved after exiting to the main menu.

Steps to recreate:
1) Open any editor with the undo function available.
2) Make some changes.
3) Undo any amount of changes.
4) Make some more changes.
5) Exit to the main menu.

Upon exiting to the main menu, the changes made during step 4 will no longer be present in the preview or any editor menu.

**Comment by timofey260** [comment]
[commit](https://github.com/timofey260/RWE-Plus/commit/442fe56db2139282a26f7d90e33f281d09ad524f) has been created and soon will be posted a new release
thank you for support
