### ISSUE TITLE
Crash on project opening after resize

### ISSUE THREAD

**Issue by ddemile** [timofey260/RWE-Plus#21]
I resized the level and the editor crashed, i can't open it anymore.
Here is the error: 

![image](https://github.com/timofey260/RWE-Plus/assets/104416229/ab0710e9-d31a-4103-9fca-7ea53517c424)

**Comment by ddemile** [comment]
Here a the files

[entre_cour](https://github.com/timofey260/RWE-Plus/assets/104416229/33d9132c-ff8c-4432-a2ec-14ca1a899f9d)
[entre_cour.txt](https://github.com/timofey260/RWE-Plus/files/11497981/entre_cour.txt)
[entre_cour.wep.txt](https://github.com/timofey260/RWE-Plus/files/11497989/entre_cour.wep.txt)
i needed to add .txt to after wep to able to upload it

**Comment by ddemile** [comment]
i found what the problem was , it was because extraTiles (in the .wep file) was set [null, null, null, null] for an unknown reason

**Comment by timofey260** [comment]
what have you tried to resize?

**Comment by ddemile** [comment]
I resized the level with the Level Size tool
