### ISSUE TITLE
Rendering problems

### ISSUE THREAD

**Issue by Perlegel** [timofey260/RWE-Plus#27]
Hello, it seen that my level can't render due to an error.
here is the code:
<img width="847" alt="Capture d'écran 2023-06-01 003131" src="https://github.com/timofey260/RWE-Plus/assets/135178940/dc0f5350-9799-4707-bbd7-1d529fdf9fb9">

**Comment by timofey260** [comment]
Let me see level txt file

**Comment by Perlegel** [comment]
> Let me see level txt file

[DB_01.txt](https://github.com/timofey260/RWE-Plus/files/11626975/DB_01.txt)

**Comment by Perlegel** [comment]
> Let me see level txt file

[DB_01.txt](https://github.com/timofey260/RWE-Plus/files/11626975/DB_01.txt)

**Comment by Perlegel** [comment]
> Let me see level txt file
[DB_01.txt](https://github.com/timofey260/RWE-Plus/files/11626992/DB_01.txt)

**Comment by timofey260** [comment]
as far as i see, the problem is what drizzle don't have Asphalt material
RWE+ also shows asphalt material as notfound texture

**Comment by timofey260** [comment]
not only asphalt material is missing, but non-slip metal, cliff, steel, megatrash are too

**Comment by timofey260** [comment]
drizzle supports only vanilla editor materials and effects

**Comment by timofey260** [comment]
To solve this problem, you can either remove all materials OR use comms editor as render itself

**Comment by Perlegel** [comment]
i See thank you !
