### ISSUE TITLE
Layer Color in Tileeditor

### ISSUE THREAD

**Issue by LaVADraGoN** [timofey260/RWE-Plus#28]
When you are on the third level in the tile editor. And especially then when fill the 3th layer, it's just pure black, you can't see what's on the previous layers. The official editor uses green and red to differentiate between them. Short, the higher you go, the worse it gets.
I use the classic ui right now. Is there a way to adjust the color and opacity in the files im not aware of?

I figured it out by reducing the Geometry editor main layer alpha to 128, at least i can see something now.
but the color of the layer dosnt seem to do anything.
			
"layer1": [255, 0, 0] is red?
"layer2": [0, 0, 255] is blue?

still grayscale for me.

**Comment by timofey260** [comment]
![image](https://github.com/timofey260/RWE-Plus/assets/69044246/e2bf3f6d-2f96-4cd8-97bc-902eb6f1c46e)

what do you exactly mean by pure black?
you can see other 2 layers always if nothing blocks them
maybe i misunderstood you?

**Comment by LaVADraGoN** [comment]
Here a screenshot of the newscene. With the default configs.
![Anmerkung 2023-06-10 L1](https://github.com/timofey260/RWE-Plus/assets/9208059/d1084e17-12be-4079-9770-d5d53b1bf406)
Layer 1 looks normal, all layer thogether looks normal to me.

![Anmerkung 2023-06-10 L3](https://github.com/timofey260/RWE-Plus/assets/9208059/ad7aad90-ba56-404a-adcb-8c937b98fccf)
If you on layer Layer 2 or 3 the layer under it are black, you can only see a bit brighter the special overlay tiles.
It behaves exactly the same in the tileeditor.

i also have a warning when making a new file
it spams: "libpng warning: ICCP: Known incorrect sRGB Profile" in the console

I hade made some adjustments for the config: With this settings.
		"primarylayeralpha": 160,
		"secondarylayeralpha": 64,
i can see all layers together, but they look a bit off, hard to tell what layer is what. This is the result:

![Anmerkung 2023-06-10 L3 Config change](https://github.com/timofey260/RWE-Plus/assets/9208059/2fcc5050-1558-429c-8575-4315b3c52fc6)

Here the Typo in the Background is on Layer 1 ,but it looks brighter. The foreground is multi to black. With some distinction in the layers. Therefore is hard to tell intuitive without colors.

**Comment by timofey260** [comment]
so you want a normal leditor style render(to show all layers same with coloring different layers to different colors)?

Error in console just says what incorrect profile for loaded tiles and props and it can be ignored

**Comment by timofey260** [comment]
do you want for top layers be more brighter to see them?

**Comment by LaVADraGoN** [comment]
It would be nice if I can assain an color overlay to the differend layers if possible, or alternative just compare layer 1 with layer 3 ,or switch one layer off if needed.
I would help with big detailed scenes where you dont fill every thing up and search for the holes between the layers.

Thats all, i wanted to know i have some difficulty to read the scenes sometimes with the default settings.

**Comment by timofey260** [comment]
https://github.com/timofey260/RWE-Plus/assets/69044246/401efeea-ab26-4a00-bd86-d9c665e14c05

how about toggling layers visibility to compare them more easily?

**Comment by LaVADraGoN** [comment]
That would be awesome if this is where a permanent option to edit this way, a hint that a layer is hidded is also nice, so it can be switch on if needed again.

**Comment by timofey260** [comment]
![image](https://github.com/timofey260/RWE-Plus/assets/69044246/705245a0-a460-482c-81fe-57a4e1348f4e)

what about that?

**Comment by LaVADraGoN** [comment]
Thx for your awesome work, I appriciate it
