### ISSUE TITLE
Allow the effect brush to place single pixels

### ISSUE THREAD

**Issue by mayhemmmwith3ms** [timofey260/RWE-Plus#29]
When painting certain effects (mostly ones in the Plants (Individual) category), the current minimum brush size of 3x3 cells is too large to correctly place and adjust the effects, and having access to a 1x1 cell brush would make these effects much easier to place. This is already a feature in the official level editor, and your cursor is automatically set to 1x1 when placing Plants (Individual) effects.

**Comment by timofey260** [comment]
will be added in next release
