### ISSUE TITLE
Rectangle size indicator becomes incorrect when changing zoom

### ISSUE THREAD

**Issue by mayhemmmwith3ms** [timofey260/RWE-Plus#3]
The tile size indicator for the placement rectangle (when holding RMB) is incorrect at any zoom level outside of the default zoom set when entering an editor. 
![indicatordemo](https://user-images.githubusercontent.com/62633210/223965454-0b4ef8ad-f876-4690-a90c-2541b3747c78.png)

**Comment by timofey260** [comment]
bug fixed in 2.0.2
thanks for support!
