### ISSUE TITLE
water level broken

### ISSUE THREAD

**Issue by Zer0Cip** [timofey260/RWE-Plus#31]
![Screenshot (936)](https://github.com/timofey260/RWE-Plus/assets/139066440/9aed3bba-b778-4eae-a89e-1070d04995e6)
![Screenshot (935)](https://github.com/timofey260/RWE-Plus/assets/139066440/6436f54a-dbfa-45a2-9d80-15606dfb3535)
i already restarted the campaign and relaunched the game but the water level doesn't match

**Comment by timofey260** [comment]
will be fixed in next patch

**Comment by timofey260** [comment]
does the water level changes if you raise it in editor?

**Comment by timofey260** [comment]
it seems like issue you had not showing for me

**Comment by Zer0Cip** [comment]
sry didnt get any notification when you commented, well i manually changed the white box which seemed to cause this

**Comment by Zer0Cip** [comment]
btw no it didnt, just made the white square back to its default size and the problem was fixed

**Comment by timofey260** [comment]
so when you change box size manually instead of mouse, water level turns off, but when you use mouse it doesn't?

**Comment by Zer0Cip** [comment]
no if the size is changed in anyway that isnt the normal number jumps it breaks

**Comment by timofey260** [comment]
what is normal number?

**Comment by Zer0Cip** [comment]
like in jumps of 72 / 43

**Comment by timofey260** [comment]
i have test level where i turned water to level 9 and changed level size
![image](https://github.com/timofey260/RWE-Plus/assets/69044246/3fe95dbe-aeb8-4117-99d4-a9df429ed76e)
but in the level the water line stays same
![image](https://github.com/timofey260/RWE-Plus/assets/69044246/60297a62-b56d-4b80-bc37-de6c2f582d28)
txt also shows what water level is 9
![image](https://github.com/timofey260/RWE-Plus/assets/69044246/f1548c47-d2ad-4357-b919-42cf9d7fc834)
can you show what level of water txt file has and how it's changing based on level size?

**Comment by Zer0Cip** [comment]
i dont have it saved anymore sadly

**Comment by Zer0Cip** [comment]
maybe try a new level and first change it then add water?

**Comment by timofey260** [comment]
this issue will be closed as stale
