### ISSUE TITLE
text overlapping

### ISSUE THREAD

**Issue by Zer0Cip** [timofey260/RWE-Plus#33]
![Screenshot (975)](https://github.com/timofey260/RWE-Plus/assets/139066440/f3f505f5-9a52-4c41-9749-6ed1b5b9eadc)

**Comment by Zer0Cip** [comment]
oh and also idk if its intended but the camera overlaps the grey area on the left

**Comment by timofey260** [comment]
yeah, i know that problem existed, will be fixed in next patch
same for camera overlaps
i'm currently working on rw mod rn so don't have much time for rwe+
