### ISSUE TITLE
Slopes can be placed in illegal configurations.

### ISSUE THREAD

**Issue by solthas** [timofey260/RWE-Plus#34]
Because slopes can be placed in any rotation at any location, it's possible to place them in illegal configurations that the game will not generate collision for. It might be better to have them work like in the official editor where we do not rotate them manually and instead the auto-rotate to make a legal configuration.

**Comment by timofey260** [comment]
what about adding X mark on slopes what wouldn't be with collisions, but still would be visible?
you can fill all legal cells with rmb if you want

**Comment by solthas** [comment]
Hey that would work for me.
