### ISSUE TITLE
Overlapped Tiles Feature?

### ISSUE THREAD

**Issue by MizzyMizi** [timofey260/RWE-Plus#38]
Feature request, Waterfront facility levels feature overlapped thick beams and pillar segments
Holding F while correct geometry but incorrect tiling is present should allow you to place a tile overlapped with another one

**Comment by MizzyMizi** [comment]
it might actually be better to have it completely ignore geometry, the ECNIUS rooms have wall vents partly overlapped with the geo

**Comment by timofey260** [comment]
Will be added in next release
