### ISSUE TITLE
Issues with rendering Props/adding custom props

### ISSUE THREAD

**Issue by InvaderBatflight** [timofey260/RWE-Plus#39]
The program will not open any levels after adding custom solid props. And drizzle still has issues with rendering certain props that are rotated. 
![rendererror](https://github.com/timofey260/RWE-Plus/assets/146295405/8f3f1ce7-62e0-4ba8-accc-ca751031cd82)
![beforerender](https://github.com/timofey260/RWE-Plus/assets/146295405/449762a2-5349-487d-be7c-d0d87804666c)
![afterrender](https://github.com/timofey260/RWE-Plus/assets/146295405/5844f237-00a2-4ebd-a0f5-a03289992a59)
![rweproblems](https://github.com/timofey260/RWE-Plus/assets/146295405/1d7a5b38-eaea-4c50-b733-18d9a4c486fa)

**Comment by timofey260** [comment]
Try update community drizzle version

**Comment by InvaderBatflight** [comment]
Someone told me to do that, but it didn't seem to work. 

> Try update community drizzle version

**Comment by timofey260** [comment]
You can send props to me and I'll fix them in new version. Not sure about drizzle

**Comment by InvaderBatflight** [comment]
[Coffin Props.txt](https://github.com/timofey260/RWE-Plus/files/12877440/Coffin.Props.txt)
![Coffin Props](https://github.com/timofey260/RWE-Plus/assets/146295405/cd309fda-3bb0-4e4f-a2eb-5baf039cc48d)
It's strange, because I can add soft props and they work just fine. But if I try to add any other type of prop it crashes.

**Comment by timofey260** [comment]
oh i see
maybe prop sz is wrong

**Comment by timofey260** [comment]
let me try to fix it

**Comment by timofey260** [comment]
[#nm:"Coffin Props", #tp:"variedStandard", #colorTreatment:"bevel", #bevel:3, #pxlSize:point(340,340), #repeatL:[4], #vars:4, #tags:[], #layerExceptions:[], #notes:[]]
try using this line instead
