### ISSUE TITLE
Light Flatness saved as non-positive, causing lightmap to not render

### ISSUE THREAD

**Issue by BluSalient** [timofey260/RWE-Plus#40]
(using 2.5.4)

In addition to the centering/black pixel issue fixed in 2.5.4, I found that the lightmap was not rendering because flatness was being saved as a negative number or zero (I found that it must be positive to render):

![improper](https://github.com/timofey260/RWE-Plus/assets/110735552/1bdc06ca-413c-437f-8f2d-8c56384b2bd8)

(Which could be why _pushing the lightmap to be border_ with numpad 8 (Light Flatness+) fixed the issue despite undesirably offsetting the lightmap)

Attached is a version of the leditor project (along with the lightmap) I used that _didn't_ render the lightmap.
![lt_lookout](https://github.com/timofey260/RWE-Plus/assets/110735552/731e0f4a-33ac-4b68-a242-1065bbcea39c)
[lt_lookout.wep.txt](https://github.com/timofey260/RWE-Plus/files/13531146/lt_lookout.wep.txt)
[lt_lookout.txt](https://github.com/timofey260/RWE-Plus/files/13531150/lt_lookout.txt)

Light flatness 0 or -63 (rendered manually with the Drizzle GUI):
![lt_lookout_1](https://github.com/timofey260/RWE-Plus/assets/110735552/0090d229-3569-4078-9ea0-5314a5b25cb7)

Light flatness 1 (rendered manually with the Drizzle GUI): 
![lt_lookout_1](https://github.com/timofey260/RWE-Plus/assets/110735552/4dec4e19-ace6-4636-9526-67a0bbb2d63c)

**Comment by timofey260** [comment]
will be fixed in next release
