### ISSUE TITLE
Suggestion: Switch applied effect type

### ISSUE THREAD

**Issue by MizzyMizi** [timofey260/RWE-Plus#46]
So when you have an effect maybe Melt for example this option would allow you to switch it to any other effect, so
Melt into Slime or Rust, Wire, Chains, Growers ect.

Effects like black goo and some plants might need to be restricted to their own group sense they only accept 0 and 100?

**Comment by timofey260** [comment]
Any further updates won't be added to rwe+ because I'm working on rwee

**Comment by timofey260** [comment]
Due to the recent need for patch, the feature will be added
