### ISSUE TITLE
ISSUE: Concrete slopes do not render correctly?

### ISSUE THREAD

**Issue by MizzyMizi** [timofey260/RWE-Plus#47]
Do we know if this is an issue with RWE+ or with drizzle?
![20240406180540_1](https://github.com/timofey260/RWE-Plus/assets/111175647/48660955-0d75-4fbb-b1fc-c52638e16a5d)

**Comment by timofey260** [comment]
What drizzle and rwe+ version are you using?

**Comment by MizzyMizi** [comment]
Ah my bad, it seems to be working well now. Thanks for your time.
