### ISSUE TITLE
camera issue when rendering

### ISSUE THREAD

**Issue by BwueBerryYoghurt** [timofey260/RWE-Plus#48]
it opens the folder but there are no images rendered.
![RenderError](https://github.com/timofey260/RWE-Plus/assets/167615250/71f048b1-325d-4f35-beb9-7c3195de31cb)

**Comment by timofey260** [comment]
Something is wrong with effect settings, contact slime cubed for rendering part

**Comment by BwueBerryYoghurt** [comment]
I have done some more testing, and this issue appears whenever using the "Fuzzy Growlers" effect, removing it fixes the issue.

**Comment by timofey260** [comment]
might be issue with effect layers if that's an option
