### ISSUE TITLE
I can't find where to open the editor??

### ISSUE THREAD

**Issue by corkceiling** [timofey260/RWE-Plus#49]
I've looked around everywhere in all the folders, but I can't find out where to open the actual editor

**Comment by timofey260** [comment]
Have you downloaded latest rar release wor windows or Linux?

**Comment by corkceiling** [comment]
Though I don't quite understand what you are saying (I'm just starting out with Rain World modding), I supposedly have the latest version of the editor. I am on Windows

**Comment by timofey260** [comment]
https://github.com/timofey260/RWE-Plus/releases/tag/2.6.2
This thing

**Comment by corkceiling** [comment]
I'm pretty sure that I do have the latest version. I even deleted and redownloaded it just now to make sure. So It should all be working correctly, but the problem is that I cannot find what file to open the editor itself from. The official editor has an exe file to open, so I was searching for one of those. However after looking through pretty much all the files, I could not find where to actually open the editor. So everything should be up to date, I just can't find where to open the editor.

**Comment by timofey260** [comment]
There should be an exe in rar file

**Comment by corkceiling** [comment]
After a ton of messing around with trying to find then open the rar file, I managed to find the editor!! Thank you for your help :>
