### ISSUE TITLE
Certain tiles are missing from 'tiles as prop' in prop editor

### ISSUE THREAD

**Issue by mayhemmmwith3ms** [timofey260/RWE-Plus#5]
'tiles as prop' 26 and 27 are missing from the prop menu category list (these are present in the official editor pre-downpour) as well as the Vertical Pipe prop from tiles as prop 13 (other individual props may be missing but this is the only one i've found). This means anything in the categories below Temple Stone in the tile editor are unable to be used as props.

**Comment by timofey260** [comment]
Commit was created and in 2.1 will be solved
thank you for support!
