### ISSUE TITLE
Unable to render due to windows being unable to find a name

### ISSUE THREAD

**Issue by BlockByte2008** [timofey260/RWE-Plus#50]
![image](https://github.com/timofey260/RWE-Plus/assets/106450196/e6bd50c9-348f-4c7f-9369-109bd80534d2)

i believe a possible reason is that i transferred this from a computer with a different account name, but i don't know if there is a way to change the name it checks for.

**Comment by timofey260** [comment]
#23

**Comment by timofey260** [comment]
Closed due to issue being stale
