### ISSUE TITLE
Render fails

### ISSUE THREAD

**Issue by SeemlyQuasar620** [timofey260/RWE-Plus#51]
Whenever we hit render it gives an error message and it fails. 
![image](https://github.com/timofey260/RWE-Plus/assets/82222141/f27bcfd9-8b18-446d-8a34-b7f4e4c8a73c)

It is looking for "c:\Users\FIRSTNAME" but the folder is actually called "c:\Users\FIRSTNAME LASTNAME" with a space between the two. I can't find a configuration file or settings menu to try and correct it.

**Comment by timofey260** [comment]
#23 
try using directory that doesn't have spaces

**Comment by SeemlyQuasar620** [comment]
How do I change the directory?

**Comment by timofey260** [comment]
move it somewhere else

**Comment by timofey260** [comment]
Closed due to issue being stale
