### ISSUE TITLE
Level Renders wont save

### ISSUE THREAD

**Issue by Bombaboo** [timofey260/RWE-Plus#53]
Hello, im new to both github and the RWE+. Basically im having a problem with saving the level renders. I click on the "Render" button, it leads me to the "Levels" folder but my level is not there. If you could help me id really appreciate it :), thanks

**Comment by timofey260** [comment]
Anything in console?

**Comment by Bombaboo** [comment]
I fear I don't know what you're referring to '^^, do you mean the code screen that opens along with rwe?

**Comment by timofey260** [comment]
yes, any info it shows?
also you can refer to #23

**Comment by Bombaboo** [comment]
I reinstalled the program and it magically works now? Guess I got lucky haha
Thank you for your time either way, excited to make some levels!
