### ISSUE TITLE
Editor does not output rendered image

### ISSUE THREAD

**Issue by Nekomi4** [timofey260/RWE-Plus#62]
When attempting to render a level, it doesn't output a image, and gives an error in the console.

The log/error in question:

Initializing Zygote runtime
Starting render of 1 levels
Test_Error
Adapted light rect
\C:\Users\<user>\OneDrive\Desktop\RWE+\LevelEditorProjects\Testing\Test_Error.png
Start render
saving: Test_Error ...
Found file: 0
saved22: Test_Error
Test_Error: Render succeeded in 00:00:08.7566783
Finished rendering in 00:00:08.7721513. 0 errored, 1 succeeded
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "lingotojson.py", line 411, in renderlevelProccess
TypeError: can only concatenate str (not "WindowsPath") to str

Edit 1: Fixed bad formatting
Edit 2: This happens with a level unchanged from "new level"

**Comment by FateUnix29** [comment]
im having this issue too, with any level.

**Comment by FateUnix29** [comment]
2.6.6 also has this bug (assuming you're on 2.6.7 like me)

**Comment by FateUnix29** [comment]
the python file in specific is lingotojson.py, line 411.
i can try to fix the issue and put a PR out there.

**Comment by FateUnix29** [comment]
i patched it, trying to find the other thing where its trying to run 'c:\Users\Windows'. wackamole.
