### ISSUE TITLE
Cannot render if program is inside folder with SPACE in the name

### ISSUE THREAD

**Issue by gkykc** [timofey260/RWE-Plus#66]
See title. If I put RWE inside a folder that has a spacebar in its name, I cannot render. Suppose I put RWE inside 'Desktop/My folder', then when I try to render, I will get an error saying 'cannot find Desktop/My'.

**Comment by timofey260** [comment]
2.6.8 should've fixed that

**Comment by gkykc** [comment]
Ah thanks, I was indeed using an older version!
