### ISSUE TITLE
Long props randomly reappear when deleted (originally 'Long props do not place properly')

### ISSUE THREAD

**Issue by mayhemmmwith3ms** [timofey260/RWE-Plus#7]
~~Attempting to place any 'long prop' will place a broken invisible prop. The prop can still be selected by the remove or copy tool,~~ removing it will sometimes (inconsistently) will create a visible prop at a seemingly random position, with the default size and rotation. ~~The invisible prop will be rendered as an extremely short version of the prop placed (image attached)~~
![image](https://user-images.githubusercontent.com/62633210/227917237-83b32ee9-de66-464d-a3d0-d653f2d3d221.png)
~~A broken Drill Suspender rendered.~~

I will update this issue if i find a consistent way of reproducing any of the seemingly inconsistent events.

**Comment by timofey260** [comment]
are you tried to hold LMB when placing long prop?

**Comment by mayhemmmwith3ms** [comment]
Oops I had no idea that was how you were supposed to place long props. maybe some indication that they are placed differently than other props would be useful. Although the issue of these props reappearing in seemingly random locations when deleted is still present, even with a correctly placed prop.

**Comment by timofey260** [comment]
is long prop places when you in copy or delete mod?
i found that issue and didn't found what it places prop

**Comment by mayhemmmwith3ms** [comment]
As far as i can tell, the prop will reappear at the cursor position when the mouse is clicked while holding the delete mode key and then the mouse is quickly moved away from the deleted prop's position in the time where RWE freezes to update the deleted prop. I haven't tested with other types of props so there's a chance this is an issue for all props

**Comment by timofey260** [comment]
appear, but not placed after button was released?

**Comment by mayhemmmwith3ms** [comment]
i tested a bit more, the ones that appear after deleting a prop seem to be placed, as they can be selected by the delete & copy tool, although they have the same appearance as the prop placement preview and exist alongside the placement preview. It also does seem this issue is only present for long props. I've had 2 'fake' props appear after deleting a single one before, and they seem to sometimes reappear after being deleted regardless of mouse movement, however i do not know how to reproduce this.
Edit: the 'fake' props also persist after closing the prop editor and are rendered when rendering the room

**Comment by timofey260** [comment]
are you :
press copy/delete > press LMB > release copy/delete > release LMB?
because it's impossible for prop to be placed while delete/copy mode button is held

**Comment by mayhemmmwith3ms** [comment]
As far as i can remember i release LMB before releasing the delete key, however i do release both buttons during the time where RWE freezes to register the prop being deleted, so that may be the cause. The original prop is deleted when this issue occurs, incase that wasn't clear. The issue may have something to do with the unique way long props are placed, as the issue only occurs with them.

**Comment by timofey260** [comment]
found issue, fixed with commit
