### ISSUE TITLE
Starts up and then crashes on arch linux

### ISSUE THREAD

**Issue by Euphonit** [timofey260/RWE-Plus#72]
Hello, I am running arch Linux and downloaded RWE+ version 2.6.8 as it is the newest one for me at this time. I am totally new to python in general and It took a very long time to set up a virtual environment in my RWE folder but I did it and then finally managed to install all the dependencies but when I launch it gives me this error:
 Traceback (most recent call last):
  File "/home/daniel/Desktop/RWE+_linux/./main.py", line 10, in <module>
    manager = ProcessManager()
              ^^^^^^^^^^^^^^^^
  File "/home/daniel/Desktop/RWE+_linux/LevelProcess.py", line 23, in __init__
    self.tiles = inittolist(self.window)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/Desktop/RWE+_linux/lingotojson.py", line 334, in inittolist
    preview = loadimage(path2materialPreviews / (k + ".png"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/Desktop/RWE+_linux/files.py", line 68, in loadimage
    newpath = resolvepath(filepath)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/Desktop/RWE+_linux/files.py", line 26, in resolvepath
    path = input_path.replace("\\", "/")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Path.replace() takes 2 positional arguments but 3 were given

You can find a video of it here: https://github.com/user-attachments/assets/8fd44ed9-92d8-4139-add8-76d036c694af

**Comment by timofey260** [comment]
hopefully fixed with the latest release

**Comment by Euphonit** [comment]
You might also want to fix where inside the drizzle_linux folder there is just one folder called drizzle and the program fails to start unless you copy or move the drizzle folder inside the drizzle linux folder to the main RWE+ folder. just an issue of naming things that can easily be fixed.

**Comment by timofey260** [comment]
Oh shit did I not do that
Automation flaws
