### ISSUE TITLE
Geometry and tile rendering does not always update when making changes

### ISSUE THREAD

**Issue by mayhemmmwith3ms** [timofey260/RWE-Plus#8]
Geo and tile rendering does not update when undoing or changing editors, and geometry rendering does not update when forcing geometry in tile editor. The changes are made to the level, but display as if they had not been. Switching editors while on a Z layer other than 1 will cause the editor to display as if it was still on that layer, while it is actually reset to layer 1.

**Comment by timofey260** [comment]
A BIG sorry for making that raw release, work on patch is going
